name: mgi
description: Application de messagerie pour immeubles - MGI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  device_info_plus: ^10.0.0   # ou une version r√©cente
  google_fonts: ^6.3.3

  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  smooth_page_indicator: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  open_filex: ^4.3.4
   # HTTP & API
  http: ^1.1.0
  http_parser: ^4.0.2
  dio: ^5.3.2
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  # WebSocket
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0
  stomp_dart_client: ^1.0.0

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # Media & Files
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  
  # Audio
  flutter_sound: ^9.2.13
  audioplayers: ^5.2.1

  # WebRTC & Calling
  flutter_webrtc: ^1.2.1
  vibration: ^3.1.4

  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  timeago: ^3.6.0
  mime: ^1.0.4
  url_launcher: ^6.2.1

  # Notifications
  flutter_local_notifications: ^17.0.0

  # Loading & Animations
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Signature & PDF
  signature: ^5.4.1
  syncfusion_flutter_signaturepad: ^27.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700